### ISSUE TITLE
TorchScript Module Loading Exception

### ISSUE THREAD

**Issue by mustansarsaeed** [OpenMined/KotlinSyft#322]
Hi,

I am using syft 0.2.x. Training on mobiles works fine, but sometimes I start getting the following errors and I then keep on receiving such errors unless I restart application:

```
com.facebook.jni.CppException: istream reader failed: reading file. (validate at ../caffe2/serialize/istream_adapter.cc:32)
W/System.err: (no backtrace available)
W/System.err:     at org.pytorch.NativePeer.initHybrid(Native Method)
W/System.err:     at org.pytorch.NativePeer.<init>(NativePeer.java:18)
W/System.err:     at org.pytorch.Module.load(Module.java:23)
W/System.err:     at org.openmined.syft.execution.Plan.loadScriptModule(Plan.kt:50)
W/System.err:     at org.openmined.syft.domain.JobRepository$processPlans$2$1.subscribe(JobRepository.kt:181)
W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
W/System.err:     at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
W/System.err:     at org.openmined.syft.datasource.JobLocalDataSource$saveAsync$$inlined$apply$lambda$1.subscribe(JobLocalDataSource.kt:85)
W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
W/System.err:     at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
W/System.err:     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:51)
W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12267)
W/System.err:     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
W/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
W/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
E/Syft: istream reader failed: reading file. (validate at ../caffe2/serialize/istream_adapter.cc:32)
(no backtrace available)
```

What can be the possible reasons and how can I resolve `Torchscript` module loading exception. Thanks.

**Comment by mccorby** [comment]
0.2.x does not seem to be supported anymore. Could you check if by changing to PySyft 0.5 the problem is fixed?

**Comment by mustansarsaeed** [comment]
@mccorby Thank you for the reply. Will PySyft 0.5 work under model-centric-fl i.e., compatible for both PyGrid and KotlinSyft to achieve model centric FL?
